name: tastemm
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.2.0
  - torchvision=0.17.0
  - torchaudio=2.2.0
  - pytorch-cuda=12.1
  - pyg=2.6.1
  - pip
  - pip:
      - -r requirements.txt
